---
apiVersion: v2
name: kafka-operator
version: "25.11.0-rc1"
appVersion: "25.11.0-rc1"
description: The Stackable Operator for Apache Kafka
home: https://github.com/stackabletech/kafka-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
